apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green-deployment
  labels:
    app: nginx-green
spec:
  replicas: 4
  revisionHistoryLimit: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: nginx-green
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      containers:
      - name: nginx-green
        image: nginx:latest
        ports:
        - containerPort: 80
