apiVersion: v1
kind: Service
metadata:
  name: nginx-bluegreen-service
spec:
  selector:
    app: nginx-green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30090
  type: NodePort
