apiVersion: v1
kind: ConfigMap
metadata:
  name: $APP_NAME
  namespace: $NAMESPACE
data:
  default.conf: |-
    server {
      listen       80;
      server_name   vue-test.kubernets.cn; # 生产环境域名
      location /img {             # 访问img路径下资源时，重定向到百度页面
          return 301 https://www.baidu.com;
      }
      location / {
          root  /opt/vue/dist;
          index  index.html index.htm;
          try_files $uri $uri/ /index.html;
          add_header Access-Control-Allow-Origin *;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  namespace: $NAMESPACE
spec:
  type: ClusterIP 
  selector:
    app: $APP_NAME
  ports:
  - name: http
    port: 80
    protocol: TCP 
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  namespace: $NAMESPACE
spec:
  replicas: $APP_REPLICAS
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: $IMAGE_NAME
        resources:
          limits:
            memory: $PODMEMORYGi
            cpu: $PODCPUG
          requests:
            memory: $PODMEMORYGi
            cpu: $PODCPUG
        ports:
          - containerPort: 80
            name: web
        livenessProbe:
          httpGet:
            port: web
            path: /
        readinessProbe:
          tcpSocket:
            port: web
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
            name: nginx-config
          - mountPath: /media
            name: media
      volumes:
        - name:  nginx-config  # 使用生产模式nginx配置文件
          configMap:
            name:  $APP_NAME
        - name: media          # 挂载空目录，用于存放远端资源
          emptyDir: {}
