apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: test-pvc
spec:
storageClassName: nfs-storage                   //指定通过哪个StorageClass创建pv
accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
