apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
spec:
  selector:
    matchLabels:
      app: myweb
  replicas: 3
  template:
    metadata:
      labels:
        app: myweb
    spec:
      nodeName: cn-shanghai.172.25.25.145       # 指定固定的节点
      containers:
      - name: myweb
        image: nginx
        ports:
        - containerPort: 80
