apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/https-redirect-status-code: "301"
    konghq.com/protocols: http
    konghq.com/regex-priority: "1000"
  name: go-web-ing
spec:
  ingressClassName: kong
  rules:
  - host: go-web.kubernets.cn                                   //改为自己定义的域名
    http:
      paths:
      - backend:
          service:
            name: go-web
            port:
              number: 9999
        path: /
        pathType: ImplementationSpecific
