apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/https-redirect-status-code: "301"
    konghq.com/protocols: http
    konghq.com/regex-priority: "1000"
  name: vue-ing
spec:
  ingressClassName: kong
  rules:
  - host: vue-test.kubernets.cn
    http:
      paths:
      - backend:
          service:
            name: vue
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
