apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
spec:
  containers:
  - name: qos-demo
    image: nginx
    resources:
      limits:
        memory: "500Mi"
        cpu: "700m"
      requests:
        memory: "500Mi"
        cpu: "700m"

---
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo2
spec:
  containers:
  - name: qos-demo2
    image: nginx
    resources:
      limits:
        memory: "500Mi"
      requests:
        memory: "200Mi"

---
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo3
spec:
  containers:
  - name: qos-demo3
    image: nginx
